version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres-food-reserve
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kchsdk10
      POSTGRES_DB: food_reserve_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - food-reserve-net

networks:
  food-reserve-net:
    driver: bridge

volumes:
  postgres-data:
    driver: local